### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by fabaff** [cblopez/nmapthon2#4]
On PyPI is [0.1.5](https://pypi.org/project/nmapthon2/0.1.5/) available. On GitHub is the latest tagged release is [0.1.3](https://github.com/cblopez/nmapthon2/tree/v0.1.3).

You started to publish only wheels and no source tarball on PyPI. This will probably break the build process of the distribution which are shipping `nmapthon2` as package.

**Comment by cblopez** [comment]
Updated Github releases to 0.1.5. Next releases will include the tar.
